#spring:
#  datasource:
#    username: ${DB_USERNAME:admin}
#    password: ${DB_PASSWORD:admin}
#    url: ${DB_URL:http}
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
